[package]
name = "proxy"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
pingora = { workspace = true, features = ["lb", "openssl"] }
async-trait = "0.1"
tokio = { workspace = true, features = ["full"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arc-swap = "1.7"
log = "0.4"
http = "1.0"
regex = { workspace = true }
url = "2.5"
anyhow = "1.0"

snapshot = { path = "../snapshot" }
domain = { path = "../../../control-plane/crates/domain" }
authn = { path = "../authn" }
authz = { path = "../authz" }
limits = { path = "../limits" }
prometheus = "0.13"
lazy_static = "1.4"
chrono.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
